name: autoyapf

on: 
  pull_request:
    branches: 
      - master
    paths:
      - '**.py'
 
jobs:
  label:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.10]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing PEP8
        run: |
          python -m pip install --upgrade pip
          pip install yapf
          URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          yapf -i -r -vv -p $FILES
          # URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
          # FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          # echo $FILES
      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Git Push Changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "refactor: automatic code reformatting to PEP8 by yapf"
          git push 
